### ISSUE TITLE
Error "Failed to open exefs/main.npdm!"

### ISSUE THREAD

**Issue by gingerbeardman** [cristianmiranda/friendlyROMForwarder#1]
In execfs I see only file called `main` (no extension)

`main.npdm` is missing?

**Comment by gingerbeardman** [comment]
If I put a file `main.npdm` there, then I get more errors:

```
----> Processing NPDM
Validating NPDM
Validating TitleID
Warning: TitleID 568243417b90000 is greater than 01ffffffffffffff and it's not suggested
Backing up main.npdm
Patching ACID public key

----> Processing NACP

Failed to open control/control.nacp!
```

**Comment by cristianmiranda** [comment]
Hey! I never saw you created an issue. Are you still experiencing the same?. Sorry for the late response.

**Comment by gingerbeardman** [comment]
I never tried again.

**Comment by TooTallNate** [comment]
I stumbled across this repo as well. I'm hitting the same issue. Anything I can share to help debug?

**Comment by cristianmiranda** [comment]
I believe this is an issue with exefs. I have FAT32 on my switch. Is that the case for you as well @TooTallNate ?

**Comment by TooTallNate** [comment]
I got it working by finding the necessary missing files in [this repo](https://gitlab.com/martinpham/NSP-Forwarder).
